### ISSUE TITLE
Unity-2.5D-Destruction

### ISSUE THREAD

**Issue by ColorTwist** [Nesh108/Unity-2.5D-Destruction#1]
Great work with a cool effect of destruction!

I did try to use it, but since my game is in 2D and I need the destruction object to detect OnCollierEnter2D while it is warped with 3D Box collider, it makes it harder to work.
Maybe you can also add support for 2D Box Collider when generating fractures.

I think your version is more efficient than the original one mostly when making fractures generate on runtime. Maybe you could add 2D support into it?

**Comment by Nesh108** [comment]
Hey @ColorTwist, thanks for the nice comments! :D

I think the original 2D Destruction would be most suited for the performance improvements, since you don't need the 2.5D part.
Perhaps you can see what changes I did for this and implement them in the 2D package?
Or you could use mine and swap all the 3D colliders with 2D ones.
